// File generated by Blink v0.17.0 (https://github.com/1Axen/Blink)
// This file is not meant to be edited

export declare const stepReplication: () => void
export declare namespace mechanics {
	type DamageKind = "Normal" | "Heavy" | "Lethal"
	export const damageSelfVariable: {
		on: (Listener: (Player: Player, Value: number) => void) => (() => void)
	}
	export const damageSelf: {
		on: (Listener: (Player: Player, Value: "Normal" | "Heavy" | "Lethal") => void) => (() => void)
	}
}
export declare namespace areas {
	export const loadArea: {
		on: (Listener: (Player: Player, Value: string) => Instance) => void
	}
	export const confirmAreaLoaded: {
		on: (Listener: (Player: Player, Value: void) => void) => (() => void)
	}
}
export declare namespace towers {
	type TowerRunType = "Standard" | "Practice"
	type StartTowerRun = { towerType: "Standard" | "Practice", towerName: string }
	type StartTowerRunResult = { instance: Instance, mechanics: Instance }
	export const startTowerRun: {
		on: (Listener: (Player: Player, Value: { towerType: "Standard" | "Practice", towerName: string }) => { instance: Instance, mechanics: Instance } | undefined) => void
	}
	export const requestDetailsInTower: {
		on: (Listener: (Player: Player, Value: void) => Instance) => void
	}
	export const syncElapsedTime: {
		fire: (Player: Player, Value: number) => void
		fireAll: (Value: number) => void
		fireExcept: (Except: Player, Value: number) => void
		fireList: (List: Player[], Value: number) => void
	}
}
