// File generated by Blink v0.17.0 (https://github.com/1Axen/Blink)
// This file is not meant to be edited

export declare const stepReplication: () => void
export declare namespace mechanics {
	type DamageKind = "Normal" | "Heavy" | "Lethal"
	export const damageSelfVariable: {
		on: (Listener: (Player: Player, Value: number) => void) => (() => void)
	}
	export const damageSelf: {
		on: (Listener: (Player: Player, Value: "Normal" | "Heavy" | "Lethal") => void) => (() => void)
	}
}
