// File generated by Blink v0.17.2 (https://github.com/1Axen/Blink)
// This file is not meant to be edited

export declare const stepReplication: () => void
type DamageKind = "Normal" | "Double" | "Quadruple" | "Lethal"
export declare const damageSelfVariable: {
	on: (Listener: (Player: Player, Value: number) => void) => (() => void)
}
export declare const damageSelf: {
	on: (Listener: (Player: Player, Value: "Normal" | "Double" | "Quadruple" | "Lethal") => void) => (() => void)
}
