local assets = {
	["ui/borderGlow"] = "rbxasset://.asphalt-welcome-to-hell/ui/borderGlow.png",
	["ui/fill"] = "rbxasset://.asphalt-welcome-to-hell/ui/fill.png",
	["ui/halfBorderCircle"] = "rbxasset://.asphalt-welcome-to-hell/ui/halfBorderCircle.png",
	["ui/quarterBorderCircle"] = "rbxasset://.asphalt-welcome-to-hell/ui/quarterBorderCircle.png",
	["ui/rightTriangle"] = "rbxasset://.asphalt-welcome-to-hell/ui/rightTriangle.png",
	["ui/triangularBorderSheen"] = "rbxasset://.asphalt-welcome-to-hell/ui/triangularBorderSheen.png",
	["ui/triangularSurface"] = "rbxasset://.asphalt-welcome-to-hell/ui/triangularSurface.png",
}

return assets