local assets = {
	ui = {
		borderGlow = "rbxasset://.asphalt-welcome-to-hell/ui/borderGlow.png",
		fill = "rbxasset://.asphalt-welcome-to-hell/ui/fill.png",
		halfBorderCircle = "rbxasset://.asphalt-welcome-to-hell/ui/halfBorderCircle.png",
		quarterBorderCircle = "rbxasset://.asphalt-welcome-to-hell/ui/quarterBorderCircle.png",
		rightTriangle = "rbxasset://.asphalt-welcome-to-hell/ui/rightTriangle.png",
		triangularBorderSheen = "rbxasset://.asphalt-welcome-to-hell/ui/triangularBorderSheen.png",
		triangularSurface = "rbxasset://.asphalt-welcome-to-hell/ui/triangularSurface.png",
	},
}

return assets