local assets = {
	["images/logo"] = "rbxasset://.asphalt-game/images/logo.png",
	["ui/borderGlow"] = "rbxasset://.asphalt-game/ui/borderGlow.png",
	["ui/fill"] = "rbxasset://.asphalt-game/ui/fill.png",
	["ui/halfBorderCircle"] = "rbxasset://.asphalt-game/ui/halfBorderCircle.png",
	["ui/quarterBorderCircle"] = "rbxasset://.asphalt-game/ui/quarterBorderCircle.png",
	["ui/rightTriangle"] = "rbxasset://.asphalt-game/ui/rightTriangle.png",
	["ui/triangularBorderSheen"] = "rbxasset://.asphalt-game/ui/triangularBorderSheen.png",
	["ui/triangularSurface"] = "rbxasset://.asphalt-game/ui/triangularSurface.png",
}

return assets