local audios = {
	["core/towerSfx/button"] = "rbxasset://.asphalt-welcome-to-hell/core/towerSfx/button.mp3",
	["core/towerSfx/dash"] = "rbxasset://.asphalt-welcome-to-hell/core/towerSfx/dash.mp3",
	["core/towerSfx/doubleJump"] = "rbxasset://.asphalt-welcome-to-hell/core/towerSfx/doubleJump.mp3",
	["core/towerSfx/heartbeat"] = "rbxasset://.asphalt-welcome-to-hell/core/towerSfx/heartbeat.mp3",
	["core/towerSfx/jump"] = "rbxasset://.asphalt-welcome-to-hell/core/towerSfx/jump.wav",
	["core/towerSfx/speed"] = "rbxasset://.asphalt-welcome-to-hell/core/towerSfx/speed.mp3",
	["core/towerSfx/teleport"] = "rbxasset://.asphalt-welcome-to-hell/core/towerSfx/teleport.mp3",
	["core/towerSfx/tick"] = "rbxasset://.asphalt-welcome-to-hell/core/towerSfx/tick.mp3",
	["core/towerSfx/timeCannotBeStopped"] = "rbxasset://.asphalt-welcome-to-hell/core/towerSfx/timeCannotBeStopped.mp3",
	["core/towerSfx/timeZoneEnter"] = "rbxasset://.asphalt-welcome-to-hell/core/towerSfx/timeZoneEnter.mp3",
	["core/towerSfx/timeZoneExit"] = "rbxasset://.asphalt-welcome-to-hell/core/towerSfx/timeZoneExit.mp3",
	["core/towerSfx/victory"] = "rbxasset://.asphalt-welcome-to-hell/core/towerSfx/victory.mp3",
	["core/towerSfx/vineGrab"] = "rbxasset://.asphalt-welcome-to-hell/core/towerSfx/vineGrab.mp3",
	["game/ost/001Title"] = "rbxasset://.asphalt-welcome-to-hell/game/ost/001Title.wav",
	["game/ost/003Deathbed"] = "rbxasset://.asphalt-welcome-to-hell/game/ost/003Deathbed.mp3",
	["game/ost/007MoltenHeart"] = "rbxasset://.asphalt-welcome-to-hell/game/ost/007MoltenHeart.mp3",
}

return audios