local audios = {
	core = {
		towerSfx = {
			button = "rbxasset://.asphalt-welcome-to-hell/core/towerSfx/button.mp3",
			dash = "rbxasset://.asphalt-welcome-to-hell/core/towerSfx/dash.mp3",
			doubleJump = "rbxasset://.asphalt-welcome-to-hell/core/towerSfx/doubleJump.mp3",
			heartbeat = "rbxasset://.asphalt-welcome-to-hell/core/towerSfx/heartbeat.mp3",
			jump = "rbxasset://.asphalt-welcome-to-hell/core/towerSfx/jump.wav",
			speed = "rbxasset://.asphalt-welcome-to-hell/core/towerSfx/speed.mp3",
			teleport = "rbxasset://.asphalt-welcome-to-hell/core/towerSfx/teleport.mp3",
			tick = "rbxasset://.asphalt-welcome-to-hell/core/towerSfx/tick.mp3",
			timeCannotBeStopped = "rbxasset://.asphalt-welcome-to-hell/core/towerSfx/timeCannotBeStopped.mp3",
			timeZoneEnter = "rbxasset://.asphalt-welcome-to-hell/core/towerSfx/timeZoneEnter.mp3",
			timeZoneExit = "rbxasset://.asphalt-welcome-to-hell/core/towerSfx/timeZoneExit.mp3",
			victory = "rbxasset://.asphalt-welcome-to-hell/core/towerSfx/victory.mp3",
			vineGrab = "rbxasset://.asphalt-welcome-to-hell/core/towerSfx/vineGrab.mp3",
		},
	},
	game = {
		ost = {
			["001Title"] = "rbxasset://.asphalt-welcome-to-hell/game/ost/001Title.wav",
			["006MoltenHeart"] = "rbxasset://.asphalt-welcome-to-hell/game/ost/006MoltenHeart.mp3",
		},
	},
}

return audios