# groups dont have right perms sob
# [creator]
# type = "group"
# id = 12787072

[creator]
type = "user"
id = 1275426298

[codegen]
typescript = true
style = "nested"
strip_extensions = true

[inputs.assets]
path = "assets/**/*"
output_path = "src/shared"
