# groups dont have right perms sob
# [creator]
# type = "group"
# id = 12787072

[creator]
type = "user"
id = 1275426298

[codegen]
typescript = true
style = "flat"
strip_extensions = true

[inputs.assets]
path = "assets/**/*"
output_path = "src/core/shared"

# temp until maau is stablized
[inputs.audios]
path = "audios/**/*"
output_path = "src/core/shared"
