# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json

site_name: Welcome To Hell Kitnomicon
site_url: https://welcome-to-hell.game/kitnomicon

theme:
    name: material
    font:
        text: Ubuntu
        code: Fira Code
    palette:
        scheme: slate
    features:
        - navigation.instant
        - navigation.instant.progress
        # - navigation.sections
        - navigation.indexes
        - navigation.top
        # - navigation.tabs
        # - navigation.tabs.sticky
        - announce.dismiss
        - navigation.footer
        - search.suggest
        - search.highlight
        - search.share
        - content.tooltips
        - content.code.copy
        - content.code.annotate
        - content.code.select
        - content.footnote.tooltips

nav:
    - Introduction:
          - Introduction: index.md
          - Concepts:
                - Handling Activation: concepts/handling-activation.md
    - Mechanics:
          - Button: mechanics/button.md
    - API Reference:
          - utils:
                - api-reference/utils/index.md

extra_css:
    - theme/wthdoc.css

markdown_extensions:
    - admonition
    - attr_list
    - md_in_html
    - toc:
          title: On this page
          permalink: true
    - pymdownx.details
    - pymdownx.superfences
    - pymdownx.emoji:
          emoji_index: !!python/name:material.extensions.emoji.twemoji
          emoji_generator: !!python/name:material.extensions.emoji.to_svg
          options:
              custom_icons:
                  - docs/overrides/.icons

plugins:
    - search
