title = "Welcome To Hell Technical Documentation"

[home]
enabled = true
includeReadme = false

[docusaurus]
tagline = "Welcome To Hell Technical Documentation"

[footer]
style = "dark"
copyright = "Copyright © 2024-2025 Team Fireworks"
