# This file lists tools managed by Rokit, a toolchain manager for Roblox projects.
# For more information, see https://github.com/rojo-rbx/rokit

# New tools can be added by running `rokit add <tool>` in a terminal.

[tools]
blink = "1Axen/blink@0.17.0"
luau-lsp = "JohnnyMorganz/luau-lsp@1.42.1"
stylua = "JohnnyMorganz/StyLua@2.0.2"
lune = "lune-org/lune@0.8.9"
rojo = "rojo-rbx/rojo@7.4.4"
# asphalt = "jacktabscode/asphalt@1.0.0-pre.0"
asphalt = "roblaudio/asphalt@0.8.41"
selene = "kampfkarren/selene@0.28.0"
