# This file lists tools managed by Rokit, a toolchain manager for Roblox projects.
# For more information, see https://github.com/rojo-rbx/rokit

# New tools can be added by running `rokit add <tool>` in a terminal.

[tools]
blink = "1Axen/blink@0.17.0"
luau-lsp = "JohnnyMorganz/luau-lsp@1.44.0"
stylua = "JohnnyMorganz/StyLua@2.1.0"
lune = "lune-org/lune@0.9.0"
rojo = "rojo-rbx/rojo@7.5.1"
asphalt = "jacktabscode/asphalt@1.0.0-pre.6"
selene = "kampfkarren/selene@0.28.0"
