// File generated by Blink v0.17.0 (https://github.com/1Axen/Blink)
// This file is not meant to be edited

export declare const stepReplication: () => void
type DamageKind = "Normal" | "Heavy" | "Super" | "Lethal"
export declare const damageSelfVariable: {
	fire: (Value: number) => void
}
export declare const damageSelf: {
	fire: (Value: "Normal" | "Heavy" | "Super" | "Lethal") => void
}
