return [[

================================================================================
                                    Notice
================================================================================

================================================================================
                                   License
================================================================================

================================================================================
                               Acknowledgements
================================================================================

Parts of the Kit uses Source Code from the Eternal Towers of Hell version 6 Kit,
Eternal Towers of Hell version 5.5 Kit and the Obren's Towers of Hell version
0.3 Kit.

ImNotFireMan123 has been permissioned to see the Eternal Towers of Hell version
6 Kit early and use it's Source Code as a reference implementation.

]]
