return [[

================================================================================
                              Welcome To Hell Kit
                                 Version 1.0.0
                               By Team Fireworks
================================================================================

BEFORE YOU START DOING ANYTHING, PLEASE FOLLOW THESE INSTRUCTIONS:

Set Workspace.PhysicsSteppingMethod to `Fixed`.
If you don't do this, certain moving objects may break.

Set StarterPlayer.AutoJumpEnabled to `false`, StarterGui.ScreenOrientation to
`LandscapeSensor`, and StarterPlayer.CharacterUseJumpPower to `true`.

Set MaterialService.Use2022Materials to `false` so that your tower will look the
same as it would ingame.

Move EVERYTHING in the `SetupGroups` folder to where it asks to be put, then
ungroup it.

Then, delete the `SetupGroups` folder.

================================================================================
                                  Resources
================================================================================

The Buildnomicon: https://welcome-to-hell/go/ttbb?ref=kit
This covers how to use the kit and best practices while building your tower. It
is a must read if you are submitting towers to Welcome To Hell or if this is
your first time using this kit.

The Kitnomicon: https://welcome-to-hell/go/kit-technical-docs?ref=kit
This covers technical documentation for all Mechanics and the MechanicUtils
module. It is a must read if you want to extend the kit with your own Mechanics.

Tower Submission Portal: https://welcome-to-hell/go/tsp?ref=kit
Submit towers for reviews and potential ingame consideration, has a
pre-submission checklist, and all submission reviews.

]]
