// File generated by Blink v0.17.0 (https://github.com/1Axen/Blink)
// This file is not meant to be edited

export declare const stepReplication: () => void;
export declare const loadKitMechanics: {
	on: (Listener: (Player: Player, Value: void) => Instance | undefined) => void;
};
export declare const confirmKitLoaded: {
	on: (Listener: (Player: Player, Value: void) => void) => () => void;
};
