local assets = {
	sounds = {
		button = "rbxasset://.asphalt-welcome-to-hell/sounds/button.mp3",
		conEnter = "rbxasset://.asphalt-welcome-to-hell/sounds/conEnter.mp3",
		conExit = "rbxasset://.asphalt-welcome-to-hell/sounds/conExit.mp3",
		dash = "rbxasset://.asphalt-welcome-to-hell/sounds/dash.mp3",
		doubleJump = "rbxasset://.asphalt-welcome-to-hell/sounds/doubleJump.mp3",
		heartbeat = "rbxasset://.asphalt-welcome-to-hell/sounds/heartbeat.mp3",
		jump = "rbxasset://.asphalt-welcome-to-hell/sounds/jump.wav",
		speed = "rbxasset://.asphalt-welcome-to-hell/sounds/speed.mp3",
		teleport = "rbxasset://.asphalt-welcome-to-hell/sounds/teleport.mp3",
		tick = "rbxasset://.asphalt-welcome-to-hell/sounds/tick.mp3",
		timeCannotBeStopped = "rbxasset://.asphalt-welcome-to-hell/sounds/timeCannotBeStopped.mp3",
		victory = "rbxasset://.asphalt-welcome-to-hell/sounds/victory.mp3",
		vineGrab = "rbxasset://.asphalt-welcome-to-hell/sounds/vineGrab.mp3",
	},
	ui = {
		borderGlow = "rbxasset://.asphalt-welcome-to-hell/ui/borderGlow.png",
		fill = "rbxasset://.asphalt-welcome-to-hell/ui/fill.png",
		halfBorderCircle = "rbxasset://.asphalt-welcome-to-hell/ui/halfBorderCircle.png",
		quarterBorderCircle = "rbxasset://.asphalt-welcome-to-hell/ui/quarterBorderCircle.png",
		rightTriangle = "rbxasset://.asphalt-welcome-to-hell/ui/rightTriangle.png",
		triangularBorderSheen = "rbxasset://.asphalt-welcome-to-hell/ui/triangularBorderSheen.png",
		triangularSurface = "rbxasset://.asphalt-welcome-to-hell/ui/triangularSurface.png",
	},
}

return assets