// File generated by Blink v0.17.0 (https://github.com/1Axen/Blink)
// This file is not meant to be edited

export declare const stepReplication: () => void
export declare namespace mechanics {
	type DamageKind = "Normal" | "Heavy" | "Lethal"
	export const damageSelfVariable: {
		fire: (Value: number) => void
	}
	export const damageSelf: {
		fire: (Value: "Normal" | "Heavy" | "Lethal") => void
	}
}
export declare namespace areas {
	export const loadArea: {
		invoke: (Value: string) => Promise<Instance>
	}
	export const confirmAreaLoaded: {
		fire: (Value: void) => void
	}
}
export declare namespace towers {
	type TowerRunType = "Standard" | "Practice"
	type StartTowerRun = { towerType: "Standard" | "Practice", towerName: string }
	type StartTowerRunResult = { instance: Instance, mechanics: Instance }
	export const startTowerRun: {
		invoke: (Value: { towerType: "Standard" | "Practice", towerName: string }) => Promise<{ instance: Instance, mechanics: Instance } | undefined>
	}
	export const requestDetailsInTower: {
		invoke: (Value: void) => Promise<Instance>
	}
	export const syncElapsedTime: {
		on: (Listener: (Value: number) => void) => (() => void)
	}
}
