// File generated by Blink v0.17.0 (https://github.com/1Axen/Blink)
// This file is not meant to be edited

export declare const stepReplication: () => void
export declare namespace mechanics {
	type DamageKind = "Normal" | "Harmful" | "Lethal"
	export const damageSelfVariable: {
		fire: (Value: number) => void
	}
	export const damageSelf: {
		fire: (Value: "Normal" | "Harmful" | "Lethal") => void
	}
}
