// File generated by Blink v0.17.0 (https://github.com/1Axen/Blink)
// This file is not meant to be edited

export declare const stepReplication: () => void;
export declare const loadKitMechanics: {
	invoke: (Value: void) => Promise<Instance | undefined>;
};
export declare const confirmKitLoaded: {
	fire: (Value: void) => void;
};
