--!strict

-- WELCOME TO HELL: COMMENT CORE MECHANIC WARNING

local TODO = "TODO"

return table.freeze({
	-- Logic
	Format = TODO,
	Math = TODO,
	Typeof = TODO,
	Wait = TODO,

	-- Control Flow
	Compare = TODO,
	If = TODO,
	Repeat = TODO,
	Spawn = TODO,

	-- Inputs
	GetAttribute = TODO,
	GetProperty = TODO,
	GetTag = TODO,
	GetVariable = TODO,
	GetTower = TODO,
	GetChild = TODO,
	Nil = TODO,

	-- Outputs
	Activate = TODO,
	SetAttribute = TODO,
	SetProperty = TODO,
	SetTag = TODO,
	SetVariable = TODO,
	NewInstance = TODO,
})
